name: Build and push on tag CircleCI without CGAL docker image

on:
  push:
    tags:
      - "*"

jobs:
  jobs:
    doxygen-docker-build:
      uses: ./.github/docker_build_push.yml
      with:
        dockerfile-path: Dockerfile_for_circleci_image_without_cgal
        docker-image-name: ci_for_gudhi_wo_cgal
        image-tag: ${GITHUB_REF#refs/tags/}
