name: Build and push on tag doxygen docker image

on:
  push:
    tags:
      - "*"

jobs:
  jobs:
    doxygen-docker-build:
      uses: ./.github/docker_build_push.yml
      with:
        dockerfile-path: Dockerfile_for_doxygen_circleci_image
        docker-image-name: doxygen_for_gudhi
        image-tag: ${GITHUB_REF#refs/tags/}
