name: Build and push on tag pip docker image

on:
  push:
    tags:
      - "*"

jobs:
  pip-docker-build:
    uses: ./.github/docker_build_push.yml
    with:
      dockerfile-path: Dockerfile_for_pip
      docker-image-name: pip_for_gudhi
      image-tag: ${GITHUB_REF#refs/tags/}
